// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YtrV9-QflyJfJCTiNXpO6dRN8cm86og',
    appId: '1:882654272400:web:5305e0ca1a16b11210f115',
    messagingSenderId: '882654272400',
    projectId: 'kawader-fe347',
    authDomain: 'kawader-fe347.firebaseapp.com',
    storageBucket: 'kawader-fe347.appspot.com',
    measurementId: 'G-R6719729KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNyaSXwOw6xbk0HKmBvnsMxsRahuIgdZ0',
    appId: '1:882654272400:android:8f42cb03b775d6d110f115',
    messagingSenderId: '882654272400',
    projectId: 'kawader-fe347',
    storageBucket: 'kawader-fe347.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6pLDHzjhIaxRLFfyX6XqB6VPsbQFgSgI',
    appId: '1:882654272400:ios:e9628a1d7a95293a10f115',
    messagingSenderId: '882654272400',
    projectId: 'kawader-fe347',
    storageBucket: 'kawader-fe347.appspot.com',
    androidClientId: '882654272400-ke0095lumr5h82ipqhd4v8r5rt5rj8lu.apps.googleusercontent.com',
    iosBundleId: 'com.sham.sahamapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6pLDHzjhIaxRLFfyX6XqB6VPsbQFgSgI',
    appId: '1:882654272400:ios:91b84ef0272b6a5110f115',
    messagingSenderId: '882654272400',
    projectId: 'kawader-fe347',
    storageBucket: 'kawader-fe347.appspot.com',
    androidClientId: '882654272400-ke0095lumr5h82ipqhd4v8r5rt5rj8lu.apps.googleusercontent.com',
    iosBundleId: 'com.example.sham',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6YtrV9-QflyJfJCTiNXpO6dRN8cm86og',
    appId: '1:882654272400:web:9ee2949a028511b510f115',
    messagingSenderId: '882654272400',
    projectId: 'kawader-fe347',
    authDomain: 'kawader-fe347.firebaseapp.com',
    storageBucket: 'kawader-fe347.appspot.com',
    measurementId: 'G-10HFLGJW5G',
  );

}